version: 2

release_config: &release_config
  working_directory: /go/src/github.com/bluele/hypermint
  docker:
    - image: golang:1.12.4-stretch
  environment:
    BUILD_DIR: ./build

jobs:
  build:
    working_directory: /go/src/github.com/bluele/hypermint
    docker:
      - image: golang:1.12.4-stretch
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: "build"
          command: |
            make build
      - run:
          name: "test"
          command: |
            make test

  contract-test:
    working_directory: /go/src/github.com/bluele/hypermint
    docker:
      - image: rust:1.34.1-stretch
    steps:
      - checkout
      - run:
          name: "test"
          command: |
            cd hmc && cargo test

  e2e-test:
    working_directory: /go/src/github.com/bluele/hypermint
    docker:
      - image: bluele/go-rust:0.1.0
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: "test"
          command: |
            make e2e-test

  pre-release:
    <<: *release_config
    steps:
      - checkout
      - run:
          name: "check if branch name is valid"
          command: |
            export VERSION=$(cat version)
            echo "VERSION is $VERSION"
            echo "CIRCLE_BRANCH is $CIRCLE_BRANCH"
            if [ "release/${VERSION}" != "${CIRCLE_BRANCH}" ]; then
              exit 1
            fi

  release:
    <<: *release_config
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2f:29:92:8a:ae:d0:d4:80:ed:3b:6b:6e:1f:e6:94:44"
      - checkout
      - run:
          name: "publish a version tag"
          command: |
            export VERSION=$(cat version)
            git tag $(cat version)
            git push origin $(cat version)

workflows:
  version: 2
  test-suite:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - contract-test:
          filters:
            tags:
              only: /.*/
      - e2e-test:
          filters:
            tags:
              only: /.*/
          requires:
            - build
  pre-release:
    jobs:
      - pre-release:
          filters:
            branches:
              only: /release\/v[0-9]+\.[0-9]+\.[0-9]+/
  release:
    jobs:
      - release:
          filters:
            branches:
              only: master
